feat(apip/flask/signup): add signup endpoints
- 1 post to generate a signup request (email is sent)
- 1 post transform request into account (activation)
- There is still no expiration to signup requests
- Only one signup request per user at a time

diff --git a/featuring-flask-api/scripts/gunicorn-runner b/featuring-flask-api/scripts/gunicorn-runner
--- a/featuring-flask-api/scripts/gunicorn-runner
+++ b/featuring-flask-api/scripts/gunicorn-runner
@@ -6,4 +6,15 @@ readonly SETTINGS=$SOURCE/featuring/settings
 
 [ -z "$SETTINGS_ENVIRON" ] && export SETTINGS_ENVIRON=featuring.settings.devel
 [ -z "$LOGCONFIG_ENVIRON" ] && export LOGCONFIG_ENVIRON=featuring.settings.logconfig.devel
+
+if [ -z "$MANDRILL_USERNAME" ]; then
+  echo "MANDRILL_USERNAME must be defined. Aborting" 1>&2
+  exit 1
+fi
+
+if [ -z "$MANDRILL_PASSWORD" ]; then
+  echo "MANDRILL_PASSWORD must be defined. Aborting" 1>&2
+  exit 1
+fi
+
 gunicorn --chdir=$SOURCE --config=$SETTINGS/gunicorn.py featuring.wsgi:app
